version: '3'
services:
  rpi-monitor:
    image: michaelmiklis/rpi-monitor:latest
    container_name: rpi-monitor
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /opt/vc:/opt/vc
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /boot:/boot
      - /sys:/dockerhost/sys:ro
      - /etc:/dockerhost/etc:ro
      - /proc:/dockerhost/proc:ro
      - /usr/lib:/dockerhost/usr/lib:ro
    devices:
      - /dev/vchiq
      - /dev/vcsm-cma
    restart: unless-stopped
    ports:
      - 8888:8888
