version: '2.1'
services:
    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - TZ=Europe/Amsterdam
            - WATCHTOWER_MONITOR_ONLY=true
            - WATCHTOWER_CLEANUP=true
            # Ajouter un 0 en premier pour les secondes : secondes | minutes | heures | jour du mois | mois | jour de la semaine
            - WATCHTOWER_SCHEDULE= 0 0 04 ? * FRI #At 04:00 AM, only on Friday Change to suit
            - WATCHTOWER_NOTIFICATIONS=email
            - WATCHTOWER_NOTIFICATION_EMAIL_FROM=mail@janvanhartevelt.nl
            - WATCHTOWER_NOTIFICATION_EMAIL_TO=janvanhartevelt@yahoo.com
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=in-v3.mailjet.com
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=password # later invullen bij env
          #  - WATCHTOWER_HTTP_API_TOKEN=aef9d48f-5c78-4353-b851-417a21829c87{from docker.com token}
            - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=Watchtower Alert - Container Updates
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=ef70f9ff1db96afa300f8163b5dbcf1b
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=465
        restart: unless-stopped
