version: '3.3'
services:
    snippet-box:
        container_name: snippetbox
        ports:
            - 5000:5000
        volumes:
            - /home/pi/appdata/snippetbox:/app/data #map to wherever you want to map
        image: pawelmalak/snippet-box:arm
        restart: unless-stopped
