web:
  image: 'ulm0/gitlab'
  restart: always
  hostname: 'gitlab.example.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.example.com:9091'
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
  ports:
    - '9091:9090'
    - '2224:22'
  volumes:
    - '/home/pi/gitlab/config:/etc/gitlab'
    - '/home/pi/gitlab/logs:/var/log/gitlab'
    - '/home/pi/gitlab/data:/var/opt/gitlab'
