version: '2'

services:
  joomla:
    image: joomla
    restart: always
    ports:
      - 8181:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example

  joomladb:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   container_name: phpmyadmin
   environment:
   - PMA_ARBITRARY=1
   restart: always
   ports:
   - 8081:80
   volumes:
   - /sessions
